src/main/java/br/com/mobilesys/bean/PerguntaBean.java
package br.com.mobilesys.bean;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.mail.MessagingException;

import org.primefaces.context.RequestContext;

import br.com.mobilesys.exception.PromoterException;
import br.com.mobilesys.lazy.PerguntaLazy;
import br.com.mobilesys.model.Pergunta;
import br.com.mobilesys.model.Pergunta.TipoCampoResposta;
import br.com.mobilesys.model.SimNao;
import br.com.mobilesys.service.EmailService;
import br.com.mobilesys.service.PerguntaService;
import br.com.mobilesys.util.FacesUtil;

@Named
@ViewScoped
public class PerguntaBean extends AbstractExportBean implements Serializable {

	private static final long serialVersionUID = 1L;
	@Inject
	private PerguntaService perguntaService;
	@Inject
	private PerguntaLazy perguntaLazy;
//	@Inject
	private EmailService emailService;
	

	private List<Pergunta> perguntas = new ArrayList<>();
	private Pergunta pergunta = new Pergunta();

	public PerguntaBean() {
	}

	
	public void novo() throws MessagingException {
		this.pergunta = new Pergunta();
		exibirDialogCadastro();
	}

	private void exibirDialogCadastro() {
		RequestContext context = RequestContext.getCurrentInstance();
		context.execute("PF('dlgCadastro').show()");
	}

	public void editar() {
		exibirDialogCadastro();
	}

	public void salvar() {
		try {
			perguntaService.salvar(pergunta);
			exibirMensagemSucesso();
//			List<String> lista = new ArrayList<>();
//			lista.add("ivconte@gmail.com");
//			emailService.enviarEmail(lista, String.format("pergunta \" %s \" salva com sucesso.", pergunta.getDescricao()),
//					"pergunta salva com sucesso!", "");
		} catch (PromoterException e) {
			exibirMensagemErro(e);
		}

	}
	
	/*public void exportarExcel() throws IOException{
		FacesContext facesContext = FacesContext.getCurrentInstance();
		ExternalContext externalContext = facesContext.getExternalContext();
		ServletContext servletContext = (ServletContext) externalContext.getContext();
		HttpServletResponse response = (HttpServletResponse) externalContext.getResponse();
		String pathRel;
		try {
			perguntas = perguntaService.listarPerguntas();
			pathRel = servletContext.getRealPath("/WEB-INF/relatorios/relatorio_pergunta.jasper");
			ByteArrayOutputStream output = (ByteArrayOutputStream)exportService.exportarExcel(perguntas, pathRel);
			response.setContentType("application/vnd.ms-excel");
			response.addHeader("Content-Disposition", "attachment;filename=relatorio_pergunta.xls");
			response.setContentLength(output.size());
			response.getOutputStream().write(output.toByteArray(), 0, output.size());
			response.getOutputStream().flush();
			response.getOutputStream().close();
			facesContext.responseComplete();
			facesContext.renderResponse();
		} catch (PromoterException e) {
			exibirMensagemErro(e);
		}
	}*/
	
	public void exportarExcel() throws IOException{
		try {
			List<Pergunta> lista = perguntaService.listarPerguntas();
			setNomeArquivoSaida("relatorio_pergunta.xls");
			setNomeRelatorio("relatorio_pergunta.jasper");
			setLista(lista);
			processarRelatorio();
		} catch (PromoterException e) {
			FacesUtil.addErrorMessage(e.getMessage());
		}
		
	}

	private void exibirMensagemSucesso() {
		FacesUtil.addSuccessMessage("Adicionado com sucesso.");
	}

	private void exibirMensagemErro(PromoterException e) {
		RequestContext.getCurrentInstance().addCallbackParam("manterModal", true);
		FacesUtil.addErrorMessage(e.getMessage());
	}

	public void excluir() throws PromoterException {
		perguntaService.excluir(pergunta);
	}

	public List<Pergunta> getPerguntas() {
		return perguntas;
	}

	public void setPerguntas(List<Pergunta> perguntas) {
		this.perguntas = perguntas;
	}

	public Pergunta getPergunta() {
		return pergunta;
	}

	public void setPergunta(Pergunta pergunta) {
		this.pergunta = pergunta;
	}

	public TipoCampoResposta[] getTiposPergunta() {
		return TipoCampoResposta.values();
	}

	public SimNao[] getSimNao() {
		SimNao[] values = SimNao.values();
		Collections.sort(Arrays.asList(values), Collections.reverseOrder(Comparator.comparing(SimNao::ordinal)));
		return values;
	}

	public PerguntaLazy getPerguntaLazy() {
		return perguntaLazy;
	}

}

src/main/java/br/com/mobilesys/model/Pergunta.java
package br.com.mobilesys.model;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * @author Geraldo Vieira
 * 
 */
@Entity
@Table(name = "pergunta")
@ApiModel
public class Pergunta implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false, updatable = false)
	private Long id;

	@Size(min = 2, max = 255, message = "A descrição deve ter entre 2 e 255 caracteres.")
	@NotNull(message="O campo descrição deve ser preenchido.")
	@Column(name = "descricao", length = 255, nullable = false)
	private String descricao;

	@NotNull(message="O campo tipo campo resposta deve ser preenchido.")
	@Enumerated(EnumType.ORDINAL)
	@Column(name = "tipo_campo_resposta", nullable = false)
	private TipoCampoResposta tipoCampoResposta;

	@Column(name = "obrigatorio")
	private SimNao obrigatorio = SimNao.SIM;

	@Enumerated(EnumType.ORDINAL)
	@Column(name = "ativo")
	private SimNao ativo = SimNao.SIM;

	@Enumerated(EnumType.ORDINAL)
	@Column(name = "foto")
	private SimNao foto = SimNao.NAO;

	@Column(name = "mascara")
	private String mascara;

	public Pergunta() {
	}

	public Pergunta(Long id) {
		this.id = id;
	}
	
	@ApiModelProperty(position = 1, required = false, value = "id da pergunta",example="1")
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	@ApiModelProperty(position = 2, required = true, value = "descrição da pergunta.",example="Qual a capital do PR?")
	public String getDescricao() {
		return descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}
	
	@ApiModelProperty(position = 3, required = true, value = "tipo de resposta",example="2",name="tipoCampoResposta")
	public TipoCampoResposta getTipoCampoResposta() {
		return tipoCampoResposta;
	}

	public void setTipoCampoResposta(TipoCampoResposta tipoCampoResposta) {
		this.tipoCampoResposta = tipoCampoResposta;
	}
	@ApiModelProperty(position = 4, required = false, value = "define se a pergunta é obrigatória.",example="0")
	public SimNao getObrigatorio() {
		return obrigatorio;
	}

	public void setObrigatorio(SimNao obrigatorio) {
		this.obrigatorio = obrigatorio;
	}

	@ApiModelProperty(position = 5, required = false, value = "ativa/inativa a pergunta.",example="0")
	public SimNao getAtivo() {
		return ativo;
	}

	public void setAtivo(SimNao ativo) {
		this.ativo = ativo;
	}
	@ApiModelProperty(position = 6, required = false, value = "habilita/desabilita foto.",example="1")
	public SimNao getFoto() {
		return foto;
	}

	public void setFoto(SimNao foto) {
		this.foto = foto;
	}
	@ApiModelProperty(position = 7, required = false, value = "mascara",example="mascara")
	public String getMascara() {
		return mascara;
	}

	public void setMascara(String mascara) {
		this.mascara = mascara;
	}
	
	public enum TipoCampoResposta {
		INTEGER("Número Inteiro"),
		DOUBLE("Número Fracionário"),
		STRING("Alfanumérico"),
		CHECKBOX("Múltipla Escolha"),
		RADIOBUTTON("Única Escolha"),
		DATE("Data"),
		DATA_TIME("Data com Hora"),
		TIME("Hora"),
		TRUE_FALSE("Sim/Não"),
		EMAIL("E-mail"),
		CIDADE("Cidade");

		private final String descricao;

		private TipoCampoResposta(String descricao) {
			this.descricao = descricao;
		}

		public String getDescricao() {
			return descricao;
		}

		@Override
		public String toString() {
			return descricao;
		}
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((descricao == null) ? 0 : descricao.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof Pergunta))
			return false;
		Pergunta other = (Pergunta) obj;
		if (descricao == null) {
			if (other.descricao != null)
				return false;
		} else if (!descricao.equals(other.descricao))
			return false;
		return true;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Pergunta [id=").append(id).append(", descricao=")
				.append(descricao).append(", tipoCampoResposta=")
				.append(tipoCampoResposta).append(", obrigatorio=")
				.append(obrigatorio).append(", ativo=").append(ativo)
				.append(", foto=").append(foto).append(", mascara=")
				.append(mascara).append("]");
		return builder.toString();
	}
	
	
	
}

src/main/java/br/com/mobilesys/model/StatusAtivo.java
/**
 *
 */
package br.com.mobilesys.model;

/**
 * Enum para indicar o Status Ativo de um registro.
 * 
 * @author Geraldo Vieira - 29/10/2012
 * 
 */
public enum StatusAtivo {

	/**
	 * Indica que o registro esta ativo.
	 */
	ATIVO(0) {
		@Override
		public String getDescricao() {
			return "Ativo";
		}

	},
	/**
	 * Indica que o registro esta inativo.
	 */
	INATIVO(1) {
		@Override
		public String getDescricao() {
			return "Inativo";
		}

	};
	
	private int valor;
	public abstract String getDescricao();

	private StatusAtivo(int status) {
		this.valor = status;
	}


}

src/main/webapp/pergunta/pergunta.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets">

<ui:composition template="../template.xhtml">
	<ui:define name="content">
		<h:form id="formLista">
			<p:dataTable id="perguntas" var="pergunta"
				value="#{perguntaBean.perguntaLazy}" lazy="true"
				selectionMode="single" selection="#{perguntaBean.pergunta}"
				paginator="true"
				paginatorTemplate="{RowsPerPageDropdown} {FirstPageLink} {PreviousPageLink} {CurrentPageReport} {NextPageLink} {LastPageLink}"
				rowsPerPageTemplate="5,10,15" rows="10"
				emptyMessage="Nenhum registro encontrado." reflow="true"
				style="margin-top:20px;margin-left:20px;margin-right:20px">
				<f:facet name="header">
					<h:outputText value="Pergunta" />
				</f:facet>
				<p:column headerText="Id">
					<h:outputText value="#{pergunta.id}" />
				</p:column>
				<p:column headerText="Descrição">
					<h:outputText value="#{pergunta.descricao}" />
				</p:column>
				<p:column headerText="Tipo Resposta">
					<h:outputText value="#{pergunta.tipoCampoResposta.descricao}" />
				</p:column>
				<f:facet name="footer">
					<p:outputPanel autoUpdate="true">
						<p:commandButton id="botaoNovo" value="novo" title="novo"
							icon="ui-icon-plus" action="#{perguntaBean.novo}"
							partialSubmit="true" immediate="true" update=":formCadastro">
							<p:resetInput target=":formCadastro" />
						</p:commandButton>
						<p:commandButton id="botaoEditar" value="#{msg['botao.editar']}"
							title="#{msg['botao.editar']}"
							oncomplete="PF('dlgCadastro').show()" update=":formCadastro"
							icon="ui-icon-pencil" partialSubmit="true"
							action="#{perguntaBean.editar()}"
							disabled="#{empty perguntaBean.pergunta.id}">
							<p:resetInput target=":formCadastro" />
						</p:commandButton>
						<p:commandButton id="botaoExcluir" value="#{msg['botao.excluir']}"
							title="#{msg['botao.excluir']}" update="@form"
							icon="ui-icon-trash" onclick="PF('confirma').show()"
							partialSubmit="true" type="button"
							disabled="#{empty perguntaBean.pergunta.id}" />
						<p:commandButton id="botaoExportar"
							value="#{msg['botao.exportar']}" title="#{msg['botao.exportar']}"
							ajax="false" actionListener="#{perguntaBean.exportarExcel()}" />
					</p:outputPanel>
				</f:facet>
				<p:ajax event="rowSelect" global="false"
					update="botaoEditar botaoExcluir" />
			</p:dataTable>
			<p:confirmDialog id="dialogConfirma" widgetVar="confirma"
				closable="false" header="#{msg['label.confirma']}">
				<f:facet name="message">
					<h:outputText value="#{msg['confirma.excluir']}" />
				</f:facet>
				<p:commandButton id="botaoConfirmar"
					value="#{msg['botao.confirmar']}" title="#{msg['botao.confirmar']}"
					icon="ui-icon-check" action="#{perguntaBean.excluir()}"
					update="@form" oncomplete="PF('confirma').hide()" />
				<p:commandButton id="botaoCancelar" value="#{msg['botao.cancelar']}"
					title="#{msg['botao.cancelar']}" icon="ui-icon-cancel"
					type="button" onclick="PF('confirma').hide()" />
			</p:confirmDialog>
		</h:form>



		<p:dialog header="Cadastro de Pergunta" widgetVar="dlgCadastro"
			modal="true" resizable="false" responsive="true">
			<h:form id="formCadastro">
				<p:messages id="mensagensCadastro" showSummary="true" />
				<h:panelGrid layout="grid" columns="2"
					styleClass="ui-panelgrid-blank"
					columnClasses="ui-grid-col-4,ui-grid-col-8">
					<h:outputLabel for="descricao" value="Descrição" />
					<p:inputTextarea id="descricao"
						value="#{perguntaBean.pergunta.descricao}" rows="3">
					</p:inputTextarea>

					<h:outputLabel for="tipoCampoResposta" value="Tipo de Resposta" />
					<h:selectOneMenu id="tipoCampoResposta"
						value="#{perguntaBean.pergunta.tipoCampoResposta}">
						<f:selectItem itemLabel="Selecione" itemValue=""
							noSelectionOption="true" />
						<f:selectItems value="#{perguntaBean.tiposPergunta}" />
					</h:selectOneMenu>


					<h:outputLabel for="ativo" value="Ativo"
						rendered="#{perguntaBean.pergunta.id ne null}" />
					<p:selectOneRadio id="ativo" converter="enumConverter"
						value="#{perguntaBean.pergunta.ativo}"
						rendered="#{perguntaBean.pergunta.id ne null}">
						<f:selectItems value="#{perguntaBean.simNao}" var="itemAtivo"
							itemLabel="#{itemAtivo.descricao}" />
					</p:selectOneRadio>

					<h:outputLabel for="foto" value="Foto"
						rendered="#{perguntaBean.pergunta.id ne null}" />
					<p:selectOneRadio id="foto" converter="enumConverter"
						value="#{perguntaBean.pergunta.foto}"
						rendered="#{perguntaBean.pergunta.id ne null}">
						<f:selectItems value="#{perguntaBean.simNao}" var="itemFoto"
							itemLabel="#{itemFoto.descricao}" />
					</p:selectOneRadio>
					<f:facet name="footer">
						<p:commandButton id="botaoSalvar" value="salvar" title="salvar"
							action="#{perguntaBean.salvar()}"
							update="@form :formLista:perguntas"
							oncomplete="handleCadastroClose(xhr, status, args);"
							icon="ui-icon-disk" />
						<p:commandButton id="botaoCancelar" value="cancelar"
							title="cancelar" type="button"
							onclick="PF('dlgCadastro').hide();" icon="ui-icon-cancel"
							process="@this">
						</p:commandButton>
					</f:facet>
				</h:panelGrid>
				<h:outputScript name="pergunta.js" library="js" />
			</h:form>
		</p:dialog>

	</ui:define>
</ui:composition>
</html>